# Generated by Django 2.1.3 on 2018-11-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20181117_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='request_headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
